## HungerGames 饥饿游戏配置
# 重构者: ShaneBee

# 问题反馈: 请在GitHub问题跟踪器提交问题 @ https://github.com/ShaneBeeStudios/HungerGames/issues
# 更新日志: 可在SpigotMC查看 @ --- https://www.spigotmc.org/resources/hungergames.65942/

# 更多信息: 配置文件的详细说明请见Wiki @ https://github.com/ShaneBeeStudios/HungerGames/wiki/Config.yml

# 帮助链接:
# Bukkit材料枚举: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# Bukkit标签: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Tag.html

settings:
  # 启用时，错误发生时将显示更详细的调试信息
  debug: false
  # 启用时，当玩家加入竞技场时，将向服务器所有玩家广播消息，通知有游戏可加入及还需多少玩家才能开始
  # 游戏开始时也会广播消息，通知玩家仍可加入
  # 禁用时，仅向该特定游戏的玩家广播
  broadcast-join-messages: true
  # 启用时，胜利者将向全服广播
  # 禁用时，仅向参与该特定游戏的玩家广播
  broadcast-win-messages: true
  # 游戏开始后玩家免受PvP伤害的时间（秒）
  # 设置为0以禁用
  free-roam-time: 25
  # 是否在游戏中显示倒计时Boss栏
  bossbar-countdown: true
  # 追踪棒的使用次数
  tracking-stick-uses: 8
  # 追踪棒生效所需的最小玩家数量
  players-for-tracking-stick: 5
  # 箱子中生成物品的最大/最小数量
  max-chestcontent: 5
  min-chestcontent: 1
  # 奖励箱子中生成物品的最大/最小数量
  max-bonus-chestcontent: 5
  min-bonus-chestcontent: 1
  # 当游戏剩余x秒时，将玩家传送回起点
  # 设置为'0'时不传送
  teleport-at-end-time: 30
  # 启用时，玩家通过命令加入游戏后，离开时会传送回之前的位置（即执行命令的位置）
  # 点击大厅告示牌时此设置无效
  save-previous-location: true

  # 玩家离开游戏后传送到的位置
  # 可针对每个竞技场单独设置
  # 若为'none'，则使用玩家的重生点或主世界的出生点
  global-exit-location: 'none'

# 记分板相关设置
# 不仅限于侧边栏
scoreboard:
  # 启用时，游戏中所有玩家的名称标签将被隐藏
  hide-nametags: true
  show-health:
    enabled: true
    # 生命值显示位置
    # 可选 'player_list'（玩家列表）或 'below_name'（名称下方）
    # 注意：若 'hide-nametags' 启用，'below_name' 将无效
    display-slot: player_list
    # 生命值显示方式
    # 可选 'hearts'（心形）或 'integer'（数值）
    render-type: hearts
  teams:
    # 启用时，玩家可以看到同队玩家的名称标签
    # 若 'hide-nametags' 禁用，此设置无效，名称将始终显示
    show-team-nametags: true
    # 每队允许的最大玩家数量
    max-team-size: 3
    # 启用时，队友之间可以互相伤害
    allow-friendly-fire: false
    # 启用时，队友可以看见使用隐身药水的队友
    can-see-friendly-invisibles: true
mob-spawning:
  # 是否在游戏竞技场中生成生物
  # 生物定义在 mobs.yml 文件中
  enabled: true
  # 生物生成间隔（秒）
  interval: 35
  # 每个玩家周围生成的生物数量上限
  cap-per-player: 5
reward:
  # 游戏结束时是否给予玩家奖励
  enabled: true
  # 胜利者获得的现金奖励（若不想使用金钱奖励，设置为0）
  cash: 500
  # 玩家胜利时可执行的命令
  # 可用于发放投票宝箱钥匙、GriefPrevention领地方块等
  # 示例：    <player> 将被替换为胜利者
  #commands:
  #  - 'say Hi <player>'
  #  - 'crates key give <player> vote 1'
  commands:
    - none
  # 胜利时发送给玩家的消息
  #示例：    <player> 将被替换为胜利者，支持颜色代码
  #messages:
  #  - '&7恭喜 &b<player> &7你在 &3饥饿&b游戏 中获胜，获得了一个投票钥匙'
  messages:
    - none

# 游戏中的箱子设置
chests:
  # 普通箱子
  regular:
    # 箱子中物品的最小数量
    min-content: 3
    # 箱子中物品的最大数量
    max-content: 7
  # 奖励箱子
  bonus:
    min-content: 1
    max-content: 5
    # 代表奖励箱子的方块类型
    # 使用 '#' 前缀表示方块标签
    block-types:
      - 'minecraft:barrel'
      - 'minecraft:trapped_chest'
      - '#minecraft:shulker_boxes'
    randomize:
      # 启用时，游戏开始时放置的方块将被替换
      # 方块将被替换为上方 'chests.bonus.block-types' 的第一个元素
      enabled: true
      # 在竞技场中随机放置此方块，游戏开始时将被替换
      # 可放置任意数量
      block: 'minecraft:pink_wool'
      # 随机生成的奖励箱子数量（在最小/最大值之间随机选择）
      # 若放置的方块不足，将停止生成（请确保放置的数量远大于最大值）
      min: 2
      max: 5
  # 空投箱子
  chest-drop:
    # 是否启用空投箱子
    enabled: false
    # 空投箱子的生成间隔（秒）
    interval: 30
    min-content: 1
    max-content: 5
rollback:
  # 允许玩家破坏竞技场中的方块，游戏结束后恢复
  allow-block-break: false
  # 允许玩家从物品展示框中取出物品（将被恢复）
  allow-itemframe-take: false
  # 每秒恢复的方块数量（此数值实际会除以20，每刻恢复一次）
  blocks-per-second: 500
  # 启用时，自由活动时间内不允许玩家破坏方块
  protect-during-free-roam: true
  # 防止玩家踩踏竞技场中的农作物
  prevent-trampling: true
  # 玩家可破坏的方块列表（使用 'all' 表示所有方块）
  # 使用 '#' 前缀表示方块标签
  editable-blocks:
    - '#minecraft:wool'
    - '#minecraft:dirt'
    - 'minecraft:short_grass'
    - 'minecraft:tall_grass'
    - 'minecraft:cobblestone'
    - 'minecraft:oak_planks'
    - 'minecraft:sandstone'
    - 'minecraft:stone_bricks'
    - 'minecraft:glass_pane'

## 世界边界
# 竞技场的默认世界边界设置
# 每个竞技场可通过 `/hg edit` 命令修改部分值
# 边界为客户端显示，不会影响竞技场外的其他玩家
world-border:
  # 是否为竞技场启用世界边界
  enabled: false
  # 若为true，游戏开始时将在竞技场外生成世界边界
  # 边界将根据竞技场时间倒计时缩小
  initiate-on-start: true
  # 边界倒计时开始的时间
  # 若 `initiate-on-start` 为true，边界将在此时间加速倒计时
  # （例如：60 = 游戏剩余60秒时开始倒计时）（需为30的倍数）
  countdown-start: 60
  # 边界停止缩小的时间（任意值，需小于 countdown-start）
  # （例如：若 countdown-start = 60 且 countdown-end = 30，边界将在30秒内缩小到中心）
  # （例如：若 countdown-start = 60 且 countdown-end = 55，边界将在5秒内缩小到中心）
  countdown-end: 30
  # 边界最终大小（从中心向外计算）
  final-border-size: 30
  # 世界边界的中心点
  # 可选 'first-spawn'（第一个生成点）、'random-spawn'（随机生成点）和 'arena-center'（竞技场中心）
  # 也可通过 '/hg edit' 命令为每个竞技场单独设置中心点
  center: 'arena-center'
## 观战模式
# 启用时，玩家可以观战游戏而不会干扰游戏中的玩家
spectate:
  # 默认禁用
  enabled: false
  # 玩家死亡后自动进入观战模式
  death-to-spectate: true
  # 隐藏观战玩家
  hide-spectators: true
  # 允许观战玩家飞行
  fly: true
  # 允许观战玩家聊天
  chat: false

# 游戏中的音效设置
sounds:
  # 玩家死亡时播放的音效
  death: 'ui.toast.challenge_complete'
  open-chest-drop: 'block.ender_chest.open'
