name: HungerGames
main: com.shanebeestudios.hg.plugin.HungerGames
authors: [bob7l, Spoopy, ShaneBee]
description: A Simple, fun, PvP arena plugin
version: '${version}'
website: https://github.com/ShaneBeeStudios/HungerGames
api-version: '1.13'
softdepend: [Multiverse-Core, MultiWorld, Vault, My_Worlds, GoldenEnchants, MythicMobs, PlaceholderAPI, XConomy]
